app.register_blueprint(user_blueprint)
# app.register_blueprint(course_blueprint)
# app.register_blueprint(module_blueprint)
# app.register_blueprint(progress_blueprint)
# app.register_blueprint(quiz_blueprint)
# app.register_blueprint(resource_blueprint)
